#!/bin/bash
#makes a thumbnail for video

if [ -f "$1" ]; then
    VIDFILE="$1"
    BASENAME=`basename $1`
    FILENAME=${BASENAME%%.*}
    echo "VID: $VIDFILE  FN: $BASENAME"
else
    echo "No file specified"
    exit
fi

if [[ $(file --mime-type -b "$VIDFILE") == video/* ]]; then
    DUR=`ffprobe -v error -show_entries format=duration -sexagesimal -of default=noprint_wrappers=1:nokey=1 $1`
    arry=($(echo $DUR | tr ":" "\n"))
    printf -v hour '%d\n' ${arry[0]} 2>/dev/null
    printf -v min '%d\n' ${arry[1]} 2>/dev/null
    printf -v sec '%d\n' ${arry[2]} 2>/dev/null
    echo $hour $min $sec
    hour=$(expr $hour / 2)
    min=$(expr $min / 2)
    sec=$(expr $sec / 2)
    echo $hour $min $sec

    ffmpeg -i $VIDFILE -ss $hour:$min:$sec -vframes 1  $2/$FILENAME.jpg
else
    echo "Not a video file"
    exit
fi



